CC=aarch64-rpi-linux-gnu-gcc
GCC=aarch64-rpi-linux-gnu-gcc
CXX=aarch64-rpi-linux-gnu-gcc
CFLAGS=-v
CPPFLAGS=-v
CXXFLAGS=-lstdc++

all: c-hello cpp-hello
clean:
	rm *.o


c-hello: c-hello.o
#	@echo CC=${CC}
#	@echo CPP=${CPP}
#	@echo GCC=${GCC}
#	@echo CXX=${GCC}
cpp-hello: cpp-hello
